# Generated by Django 4.2.5 on 2023-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0002_entidad_usuario_comunicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
