# Generated by Django 4.2.5 on 2023-10-22 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AplicacionPrueba', '0004_alter_comunicado_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.TextField(verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
