# Generated by Django 4.2.5 on 2023-10-22 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AplicacionPrueba', '0005_delete_curso_alter_entidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='administracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.CharField(max_length=255, verbose_name='Detalle_Corto'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha_publicación'),
        ),
    ]
