# Generated by Django 4.2.5 on 2023-10-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0006_entidad_administracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
