# Generated by Django 4.2.5 on 2023-10-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0007_alter_comunicado_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
