# Generated by Django 4.2.5 on 2023-10-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0009_alter_entidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
