# Generated by Django 4.2.5 on 2023-10-24 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0011_alter_comunicado_modificado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AplicacionPrueba.entidad'),
        ),
    ]
