# Generated by Django 4.2.5 on 2023-10-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrueba', '0012_alter_comunicado_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(upload_to='AplicacionPrueba/static/AplicacionPrueba/img/'),
        ),
    ]
